# 225229147

# Lab1. Python Functions and Numpy

### Part-I: Write a method for sigmoid function

In [1]:
import math
import numpy

In [26]:
#1)
def mysigmoid(x):
    a=1/(1+math.exp(-x))
    return a

In [27]:
#2
mysigmoid(4)

0.9820137900379085

In [28]:
#3
x=[1,2,3]
sigval=[mysigmoid(i) for i in x]
sigval

[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]

In [35]:
#4
import numpy as np
def mysigmoid(x):
    x=np.array(x)
    return 1/(1+np.exp(-x))
#5
x=[1,2,3]
sigval=mysigmoid(x)
print(sigval)

[0.73105858 0.88079708 0.95257413]


### Part II Gradient or derivative of sigmoid function

In [36]:
def sig_derivative(s):
    return s*(1-s)
sig_derivative(mysigmoid(4))

0.017662706213291107

### Part III Write a method image_to_vector()

In [39]:
def image_to_vector(image):
    length, height, depth = image.shape
    vector = image.reshape((length * height * 3, 1))
    return vector
image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                  [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
                  [[255, 255, 255], [0, 0, 0], [128, 128, 128]]])
vector = image_to_vector(image)
print(vector)

[[255]
 [  0]
 [  0]
 [  0]
 [255]
 [  0]
 [  0]
 [  0]
 [255]
 [255]
 [255]
 [  0]
 [255]
 [  0]
 [255]
 [  0]
 [255]
 [255]
 [255]
 [255]
 [255]
 [  0]
 [  0]
 [  0]
 [128]
 [128]
 [128]]


### Part IV  Write a Method normalizeRows()

In [41]:
def normalizeRows(x):
    norms = np.linalg.norm(x, axis=1, keepdims=True)
    normalized_x = x / norms
    return normalized_x

In [43]:
x = np.array([[8, 5, 4],
              [2, 1, 7],
              [3, 9, 6]])
normalized_x = normalizeRows(x)
print(normalized_x)

[[0.78072006 0.48795004 0.39036003]
 [0.27216553 0.13608276 0.95257934]
 [0.26726124 0.80178373 0.53452248]]


### Part V Multiplication and Vectorization Operations

In [45]:
#1.a) small array
x1 = [9, 2, 5]
x2 = [7, 2, 2]
a=np.multiply(x1,x2)
b=np.dot(x1,x2)
print("Multiplication:",a)
print("Dot product:",b)

Multiplication: [63  4 10]
Dot product: 77


In [46]:
#b) Large array
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0, 4, 5, 7]
x2 = [7, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 8, 5, 3]
a=np.multiply(x1,x2)
b=np.dot(x1,x2)
print("Multiplication:",a)
print("Dot product:",b)

Multiplication: [63  4 10  0  0 63 10  0  0  0 81  4 25  0  0 32 25 21]
Dot product: 338


In [53]:
#2
import numpy as np
import time

N = 1000000

# Create random vectors
x1 = np.random.rand(N)
x2 = np.random.rand(N)

# Perform multiplication and measure the time
start_time = time.time()
multiplication = x1 * x2
end_time = time.time()
multiplication_time = end_time - start_time

# Perform vectorization and measure the time
start_time = time.time()
dot_product = np.dot(x1, x2)
end_time = time.time()
dot_product_time = end_time - start_time

print("Multiplication Time:", multiplication_time)
print("Dot Product Time:", dot_product_time)


Multiplication Time: 0.002992868423461914
Dot Product Time: 0.0009682178497314453


### Part-VI: Implement L1 and L2 loss functions

In [54]:
def loss_l1(y, ypred): #defining functions
    return np.sum(np.abs(y - ypred))
def loss_l2(y, ypred):
    return np.sum(np.square(y - ypred))

In [55]:
#1 Function calling
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
l1_loss = loss_l1(y, ypred)
print("L1 Loss:", l1_loss)

L1 Loss: 1.1


In [56]:
#2
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
l2_loss = loss_l2(y, ypred)
print("L2 Loss:", l2_loss)


L2 Loss: 0.43
